### ISSUE TITLE
usage of fork

### ISSUE THREAD

**Issue by kiranpradeep** [rickfarmer/tether#1]
In proxy.c line 136, `fork()` has been used and so this shouldn't work on non jailbroken iOS devices. Was this code running in real iOS device ? The same for Android.

**Comment by rickfarmer** [comment]
Yes. This was running on a iPhone that was jail broken for testing.

**Comment by kiranpradeep** [comment]
@rickfarmer Thanks. Probably that information can be added to README.md file. Or else users might feel that library didn't work when they try on non jail broken devices.

**Comment by kiranpradeep** [comment]
Same about HTTPS support. README.md gives an impression like HTTPS is currently supported.

**Comment by rickfarmer** [comment]
Will do.  Thanks for pointing these out.

**Comment by kiranpradeep** [comment]
Thanks.
